version: "2"

volumes:
  mongo_data:
  esdata:
    driver: local

services:
  nats:
    image: "nats:0.8.0"
    entrypoint: "/gnatsd -DV"
    ports:
      - 4222:4222
      - 8222:8222
    hostname: nats

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    container_name: kibana
    environment:
      SERVER_NAME: kibana.local
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  mongo:
    restart: unless-stopped
    image: mongo:3.6.4
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    depends_on:
      - elasticsearch

  nginx:
    restart: on-failure
    image: nginx:latest
    ports:
      - 80:80
    links:
      - client
      - kibana
    depends_on:
      - client
      - kibana

  mongodbhandler:
    restart: on-failure
    image: mongodbhandler:latest
    volumes:
      - ./mongodbhandler:/usr/src/app
    links:
      - mongo
      - nats
    command: npm start
    depends_on:
      - mongo
      - nats
    tty: true
    stdin_open: true

  elasticsearchhandler:
    restart: on-failure
    image: elasticsearchhandler:latest
    volumes:
      - ./elasticsearchhandler:/usr/src/app
    links:
      - elasticsearch
      - nats
    command: npm start
    depends_on:
      - mongodbhandler
      - elasticsearch
      - nats
    tty: true
    stdin_open: true

  api:
    restart: on-failure
    image: api:latest
    ports:
      - 4001:4000
      - 8181:8181
    volumes:
      - ./api:/usr/src/app
    links:
      - mongo
      - nats
    command: npm start
    depends_on:
      - elasticsearchhandler
      - mongodbhandler
      - nats
    tty: true
    stdin_open: true

  client:
    restart: on-failure
    image: client:latest
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app
      - /app/node_modules
    links:
      - api
    command: npm start
    stdin_open: true
    depends_on:
      - api
